export type ConfigOptionType = 'switch' | 'select' | 'number' | 'text';

export type ConfigOption = {
  key: string;
  label: string;
  category: string;
  type: ConfigOptionType;
  defaultValue: string;
  options?: string[];
  min?: number;
  max?: number;
  description?: string;
};

export type ConfigCategory = {
  key: string;
  label: string;
  labelEn: string;
};

export const configCategories: ConfigCategory[] = [
  {
    key: 'connection',
    label: '连接与访问控制',
    labelEn: 'Connection & Access',
  },
  { key: 'security', label: '安全与认证', labelEn: 'Security & Auth' },
  { key: 'display', label: '显示与界面', labelEn: 'Display & UI' },
  { key: 'av', label: '音视频与编解码', labelEn: 'Audio/Video & Codec' },
  { key: 'file', label: '文件与剪贴板', labelEn: 'File & Clipboard' },
  { key: 'advanced', label: '高级设置', labelEn: 'Advanced' },
  { key: 'floating', label: '浮动窗口', labelEn: 'Floating Window' },
  { key: 'privacy', label: '隐私与录制', labelEn: 'Privacy & Recording' },
  { key: 'hide', label: '界面隐藏', labelEn: 'UI Hiding' },
];

export const configOptions: ConfigOption[] = [
  {
    key: 'access-mode',
    label: 'access-mode',
    category: 'connection',
    type: 'select',
    defaultValue: 'custom',
    options: ['custom', 'full', 'view'],
  },
  {
    key: 'enable-keyboard',
    label: 'enable-keyboard',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-clipboard',
    label: 'enable-clipboard',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-file-transfer',
    label: 'enable-file-transfer',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-camera',
    label: 'enable-camera',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-terminal',
    label: 'enable-terminal',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-remote-printer',
    label: 'enable-remote-printer',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-audio',
    label: 'enable-audio',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-tunnel',
    label: 'enable-tunnel',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-remote-restart',
    label: 'enable-remote-restart',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-record-session',
    label: 'enable-record-session',
    category: 'privacy',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-block-input',
    label: 'enable-block-input',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-remote-config-modification',
    label: 'allow-remote-config-modification',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-lan-discovery',
    label: 'enable-lan-discovery',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'direct-server',
    label: 'direct-server',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'whitelist',
    label: 'whitelist',
    category: 'security',
    type: 'text',
    defaultValue: '',
    description: 'Comma-separated IP list',
  },
  {
    key: 'allow-auto-disconnect',
    label: 'allow-auto-disconnect',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'auto-disconnect-timeout',
    label: 'auto-disconnect-timeout',
    category: 'connection',
    type: 'number',
    defaultValue: '10',
    min: 1,
    max: 9999,
    description: 'Timeout in minutes',
  },
  {
    key: 'allow-only-conn-window-open',
    label: 'allow-only-conn-window-open',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'approve-mode',
    label: 'approve-mode',
    category: 'security',
    type: 'select',
    defaultValue: 'password-click',
    options: ['password', 'click', 'password-click'],
  },
  {
    key: 'verification-method',
    label: 'verification-method',
    category: 'security',
    type: 'select',
    defaultValue: 'use-both-passwords',
    options: [
      'use-temporary-password',
      'use-permanent-password',
      'use-both-passwords',
    ],
  },
  {
    key: 'temporary-password-length',
    label: 'temporary-password-length',
    category: 'security',
    type: 'select',
    defaultValue: '6',
    options: ['6', '8', '10'],
  },
  {
    key: 'theme',
    label: 'theme',
    category: 'display',
    type: 'select',
    defaultValue: 'system',
    options: ['dark', 'light', 'system'],
  },
  {
    key: 'lang',
    label: 'lang',
    category: 'display',
    type: 'text',
    defaultValue: 'default',
    description: 'Language code',
  },
  {
    key: 'allow-auto-record-incoming',
    label: 'allow-auto-record-incoming',
    category: 'privacy',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-auto-record-outgoing',
    label: 'allow-auto-record-outgoing',
    category: 'privacy',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-auto-update',
    label: 'allow-auto-update',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-confirm-closing-tabs',
    label: 'enable-confirm-closing-tabs',
    category: 'display',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-abr',
    label: 'enable-abr',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-remove-wallpaper',
    label: 'allow-remove-wallpaper',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-open-new-connections-in-tabs',
    label: 'enable-open-new-connections-in-tabs',
    category: 'display',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-always-software-render',
    label: 'allow-always-software-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-linux-headless',
    label: 'allow-linux-headless',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-hwcodec',
    label: 'enable-hwcodec',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'peer-card-ui-type',
    label: 'peer-card-ui-type',
    category: 'display',
    type: 'select',
    defaultValue: '0',
    options: ['0', '1', '2'],
  },
  {
    key: 'peer-sorting',
    label: 'peer-sorting',
    category: 'display',
    type: 'select',
    defaultValue: 'Remote ID',
    options: ['Remote ID', 'Remote Host', 'Username'],
  },
  {
    key: 'sync-ab-with-recent-sessions',
    label: 'sync-ab-with-recent-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'sync-ab-tags',
    label: 'sync-ab-tags',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'filter-ab-by-intersection',
    label: 'filter-ab-by-intersection',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'use-texture-render',
    label: 'use-texture-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
    description: 'Platform dependent',
  },
  {
    key: 'enable-udp-punch',
    label: 'enable-udp-punch',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-ipv6-punch',
    label: 'enable-ipv6-punch',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
    description: 'Self-hosted: N, others: Y',
  },
  {
    key: 'view-only',
    label: 'view-only',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-monitors-toolbar',
    label: 'show-monitors-toolbar',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'collapse-toolbar',
    label: 'collapse-toolbar',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-remote-cursor',
    label: 'show-remote-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'follow-remote-cursor',
    label: 'follow-remote-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'follow-remote-window',
    label: 'follow-remote-window',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'zoom-cursor',
    label: 'zoom-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-quality-monitor',
    label: 'show-quality-monitor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-audio',
    label: 'disable-audio',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-file-copy-paste',
    label: 'enable-file-copy-paste',
    category: 'file',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-clipboard',
    label: 'disable-clipboard',
    category: 'file',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'lock-after-session-end',
    label: 'lock-after-session-end',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'privacy-mode',
    label: 'privacy-mode',
    category: 'privacy',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'i444',
    label: 'i444',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'reverse-mouse-wheel',
    label: 'reverse-mouse-wheel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'swap-left-right-mouse',
    label: 'swap-left-right-mouse',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'displays-as-individual-windows',
    label: 'displays-as-individual-windows',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'use-all-my-displays-for-the-remote-session',
    label: 'use-all-my-displays-for-the-remote-session',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'view-style',
    label: 'view-style',
    category: 'display',
    type: 'select',
    defaultValue: 'original',
    options: ['original', 'adaptive'],
  },
  {
    key: 'scroll-style',
    label: 'scroll-style',
    category: 'display',
    type: 'select',
    defaultValue: 'scrollauto',
    options: ['scrollauto', 'scrollbar', 'scrolledge'],
  },
  {
    key: 'edge-scroll-edge-thickness',
    label: 'edge-scroll-edge-thickness',
    category: 'display',
    type: 'number',
    defaultValue: '100',
    min: 20,
    max: 150,
  },
  {
    key: 'image-quality',
    label: 'image-quality',
    category: 'av',
    type: 'select',
    defaultValue: 'balanced',
    options: ['best', 'balanced', 'low', 'custom'],
  },
  {
    key: 'custom-image-quality',
    label: 'custom-image-quality',
    category: 'av',
    type: 'number',
    defaultValue: '50',
    min: 10,
    max: 2000,
  },
  {
    key: 'custom-fps',
    label: 'custom-fps',
    category: 'av',
    type: 'number',
    defaultValue: '30',
    min: 5,
    max: 120,
  },
  {
    key: 'terminal-persistent',
    label: 'terminal-persistent',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'trackpad-speed',
    label: 'trackpad-speed',
    category: 'display',
    type: 'number',
    defaultValue: '100',
    min: 10,
    max: 1000,
  },
  {
    key: 'disable-group-panel',
    label: 'disable-group-panel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'pre-elevate-service',
    label: 'pre-elevate-service',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-floating-window',
    label: 'disable-floating-window',
    category: 'floating',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'floating-window-size',
    label: 'floating-window-size',
    category: 'floating',
    type: 'number',
    defaultValue: '120',
    min: 32,
    max: 320,
  },
  {
    key: 'floating-window-untouchable',
    label: 'floating-window-untouchable',
    category: 'floating',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'floating-window-transparency',
    label: 'floating-window-transparency',
    category: 'floating',
    type: 'number',
    defaultValue: '10',
    min: 0,
    max: 10,
  },
  {
    key: 'keep-screen-on',
    label: 'keep-screen-on',
    category: 'display',
    type: 'select',
    defaultValue: 'during-controlled',
    options: ['never', 'during-controlled', 'service-on'],
  },
  {
    key: 'keep-awake-during-incoming-sessions',
    label: 'keep-awake-during-incoming-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'keep-awake-during-outgoing-sessions',
    label: 'keep-awake-during-outgoing-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-directx-capture',
    label: 'enable-directx-capture',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-android-software-encoding-half-scale',
    label: 'enable-android-software-encoding-half-scale',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-remote-cm-modification',
    label: 'allow-remote-cm-modification',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'remove-preset-password-warning',
    label: 'remove-preset-password-warning',
    category: 'security',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-security-settings',
    label: 'hide-security-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-network-settings',
    label: 'hide-network-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-server-settings',
    label: 'hide-server-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-proxy-settings',
    label: 'hide-proxy-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-websocket-settings',
    label: 'hide-websocket-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-remote-printer-settings',
    label: 'hide-remote-printer-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-username-on-card',
    label: 'hide-username-on-card',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-help-cards',
    label: 'hide-help-cards',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-udp',
    label: 'disable-udp',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-trusted-devices',
    label: 'enable-trusted-devices',
    category: 'security',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-tray',
    label: 'hide-tray',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-stop-service',
    label: 'hide-stop-service',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'one-way-clipboard-redirection',
    label: 'one-way-clipboard-redirection',
    category: 'file',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'one-way-file-transfer',
    label: 'one-way-file-transfer',
    category: 'file',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'sync-init-clipboard',
    label: 'sync-init-clipboard',
    category: 'file',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-logon-screen-password',
    label: 'allow-logon-screen-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-https-21114',
    label: 'allow-https-21114',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-d3d-render',
    label: 'allow-d3d-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-hostname-as-id',
    label: 'allow-hostname-as-id',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-websocket',
    label: 'allow-websocket',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-numeric-one-time-password',
    label: 'allow-numeric-one-time-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'register-device',
    label: 'register-device',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'main-window-always-on-top',
    label: 'main-window-always-on-top',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-discovery-panel',
    label: 'disable-discovery-panel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'touch-mode',
    label: 'touch-mode',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-virtual-mouse',
    label: 'show-virtual-mouse',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-virtual-joystick',
    label: 'show-virtual-joystick',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-insecure-tls-fallback',
    label: 'allow-insecure-tls-fallback',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-ask-for-note',
    label: 'allow-ask-for-note',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-change-permanent-password',
    label: 'disable-change-permanent-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-change-id',
    label: 'disable-change-id',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-unlock-pin',
    label: 'disable-unlock-pin',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-command-line-settings-when-settings-disabled',
    label: 'allow-command-line-settings-when-settings-disabled',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];

export const configOptionsMap = configOptions.reduce<
  Record<string, ConfigOption>
>((acc, opt) => {
  acc[opt.key] = opt;
  return acc;
}, {});

export function getOptionsByCategory(category: string): ConfigOption[] {
  return configOptions.filter((opt) => opt.category === category);
}

export function getModifiedCount(
  configOptions?: Record<string, string>,
): number {
  if (!configOptions) return 0;
  return Object.keys(configOptions).filter((key) => {
    const opt = configOptionsMap[key];
    if (!opt) return true;
    return configOptions[key] !== opt.defaultValue;
  }).length;
}
